### ISSUE TITLE
Error pip installing

### ISSUE THREAD

**Issue by aguilarpablo** [developmentseed/timvt#94] opened 2022-08-25 12:07 UTC
Hi,
When I am installing timvt dependencies and Uvicorn (a lightning-fast ASGI server), it appears this error:
     Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

I tried everything since check my 64-bit python version, install from https://rustup.rs/ and add the path. 

Has this happened to anyone?

**Comment by aguilarpablo** [comment] 2022-08-26 08:04
The problem was that I was using python 3.10. If you use 3.9 it works. I close the issue.

**Comment by vincentsarago** [comment] 2022-08-26 14:08
@aguilarpablo thanks for the report and the update. 

I'm still not sure where this comes from. Rust is (I think) need for one of the dependency: https://github.com/milesgranger/pyrus-cramjam but this it's python 3.10 compatible

**Comment by vincentsarago** [comment] 2022-09-08 13:35
interesting

**Comment by vincentsarago** [comment] 2022-09-08 13:36
https://github.com/developmentseed/timvt/runs/8250339868?check_suite_focus=true 

docker build is failing for the same reason. Interestingly it work fine in GitHub CI.

**Comment by vincentsarago** [comment] 2022-09-08 13:43
ok, the issue is that wheels for python 3.10 for pyrus-cramjam is only created for version >2.5.0 but starlette-cramjam requires pyrus-cramjam<2.5.0. .... so we fall back on source install but we don't have Rust in the docker image!!! 

Solutions:
- add Cargo in image
- update dependency in starlette-cramjam

**Comment by vincentsarago** [comment] 2022-09-08 14:53
this was fixed in starlette-cramjam

**Closed by vincentsarago** 2022-09-08 14:53 UTC
